# Kubernetes/Helm 설정 파일입니다. 운영 정책을 선언형으로 관리합니다.

apiVersion: v1
kind: ConfigMap
metadata:
  name: elice-minio-policy-stage
  namespace: minio-tenant-stage
data:
  elice-media-stage-policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": ["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:ListBucket"],
          "Resource": [
            "arn:aws:s3:::elice-media-stage",
            "arn:aws:s3:::elice-media-stage/*"
          ]
        }
      ]
    }
